# Generated by Django 3.2.5 on 2021-08-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210808_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.company'),
        ),
    ]
